// Generated by https://quicktype.io

export interface DetailInteresado {
    nombre:    string;
    apellidos: string;
    direccion: string;
    email:     string;
    telefono:  string;
    avatar:    string;
    viviendas: Vivienda[];
}

export interface Vivienda {
    id:                 number;
    titulo:             string;
    tipo:               string;
    direccion:          string;
    provincia:          string;
    poblacion:          string;
    avatar:             string;
    precio:             number;
    metrosCuadrados:    number;
    numeroBanos:        number;
    numeroHabitaciones: number;
}
