// Generated by https://quicktype.io

export interface DetailVivienda {
    titulo:          string;
    descripcion:     null;
    avatar:          string;
    latLng:          string;
    direccion:       string;
    codPostal:       string;
    poblacion:       string;
    provincia:       string;
    tienePiscina:    boolean;
    tieneAscensor:   boolean;
    tieneGaraje:     boolean;
    numHabitaciones: number;
    numBanos:        number;
    precio:          number;
    metrosCuadrados: null;
    tipo:            string;
}
