// Generated by https://quicktype.io

export interface DetailPropietarioResponse {
    id:                   number;
    nombre:               string;
    apellidos:            string;
    direccionPropietario: string;
    email:                string;
    telefono:             string;
    avatarPropietario:    string;
    vivienda:             Vivienda[];
}

export interface Vivienda {
    id:        number;
    titulo:    string;
    direccion: string;
    avatar:    string;
}
