// Generated by https://quicktype.io

export interface GetInteresadosListaResponse {
    id:        number;
    nombre:    string;
    apellidos: string;
    direccion: string;
    email:     string;
    telefono:  string;
    avatar:    string;
}
