// Generated by https://quicktype.io

export interface InmobiliariaResponse {
  content:          Inmobiliaria[];
  pageable:         Pageable;
  last:             boolean;
  totalPages:       number;
  totalElements:    number;
  size:             number;
  number:           number;
  sort:             Sort;
  first:            boolean;
  numberOfElements: number;
  empty:            boolean;
}

export interface Inmobiliaria {
  id:       number;
  nombre:   string;
  email:    string;
  telefono: string;
}

export interface Pageable {
  sort:       Sort;
  offset:     number;
  pageSize:   number;
  pageNumber: number;
  paged:      boolean;
  unpaged:    boolean;
}

export interface Sort {
  empty:    boolean;
  sorted:   boolean;
  unsorted: boolean;
}

export class Inmo {
  id:       number;
  nombre:   string;
  email:    string;
  telefono: string;

  constructor(){
    this.id=0;
    this.nombre="";
    this.email="";
    this.telefono="";
  }
}
